### ISSUE TITLE
Suspend does not pause execution

### ISSUE THREAD

**Issue by knoellle** [sachaos/viddy#100]
According to both the readme here and the keybind help within viddy, pressing the `s` key should pause command execution.
However, this is not the case and only the shown output is kept from updating.

# Steps to reproduce

- Open two terminals
- In the first run `viddy "date | tee /tmp/date"`
- In the second run `viddy "cat /tmp/date"`
- Press `s` in the first to "suspend execution"
- Watch the file content keep updating in the second terminal but not in the first.

# Affected Version
```
$ viddy -v
viddy version: 0.3.7
```

**Comment by sachaos** [comment]
@knoellle I've fixed this issue by https://github.com/sachaos/viddy/pull/108
