### ISSUE TITLE
Hide entries which don't include changes.

### ISSUE THREAD

**Issue by guettli** [sachaos/viddy#102]
First: Thank you very much for this tool. It is great.

Here a feature request:

Hide entries which don't include changes.

![image](https://github.com/sachaos/viddy/assets/414336/baaf46bc-6e92-4622-ba96-f1972da9fe92)

On the right side you see a lot of `+0 -0`.

Why display them? I don't see a benefit.

One reason could be: you see if nothing has change for a long time. But maybe there are better ways to show this?

The column before `+0 -0` contains a number. This number does not tell me much. Maybe this column get used to visilize the timedelta between changes?

**Comment by sachaos** [comment]
@guettli This fixed by this change. https://github.com/sachaos/viddy/pull/99
