### ISSUE TITLE
Dump data to file, so that you can share it.

### ISSUE THREAD

**Issue by guettli** [sachaos/viddy#103]
It would be great, if you could dump the history into a file, so that you can share it (or archive it).

**Comment by sachaos** [comment]
I've implemented feature to save and load history in viddy v1.0.0-rc.2.
Now, viddy store history on SQLite, and you can share that file.

https://github.com/sachaos/viddy/issues/117#issuecomment-2294818886

**Comment by sachaos** [comment]
Viddy v1.0.0 is available now.
