### ISSUE TITLE
Diff renderer treats some input as format string, prints %!!(MISSING)(NOVERB)

### ISSUE THREAD

**Issue by dnnr** [sachaos/viddy#112]
I suppose, not much further explanation is needed. See below.

**How to reproduce:**
Run `viddy -d "echo %"`

**Expected behavior:**
Render `%` with green background

**Actual behavior:**
Renders `%!!(MISSING)(NOVERB)` with green background

**Version:** 0.4.0

**Comment by phanirithvij** [comment]
related #69

**Comment by sachaos** [comment]
This bug fixed by viddy v1.0.0-rc.1 
https://github.com/sachaos/viddy/issues/117#issuecomment-2291069041

**Comment by dnnr** [comment]
Thank you!
