### ISSUE TITLE
IMPORTANT ANNOUNCEMENT: About viddy v1.0.0

### ISSUE THREAD

**Issue by sachaos** [sachaos/viddy#117]
Hello everyone,

I am the owner of this project. I am currently working on the development of viddy v1.0.0, which is almost complete and will be released soon.

In a very bold decision, I am going to replace the current viddy, which is written in Go, with Rust. There are several reasons for this, but the main one is that I will be more motivated to maintain it. Additionally, I have been dissatisfied with some aspects of the current implementation of viddy. This is not because of Go, but because my initial implementation was poor. This has led to some of the bugs currently being reported, but I believe a reimplementation will resolve some of them.

Fortunately, viddy has been integrated into many package registries. If a build is required, Rust will be needed, so changes are expected. I apologize for the inconvenience and appreciate your understanding.

In viddy v1.0.0, the following features are planned to be discontinued. If you need these features, please contact me. I will do my best to include them. As for other compatibility, I am making every effort to maintain it as much as possible.

- `-c`, `--clockwork` option
- `--pty` option
    - I've found better way to handle terminal size.

The Rust version of Viddy will be managed in this repository. I apologize to all contributors, but I plan to delete all Go code (it will remain in git). If there are strong objections, I will consider separating the repository or keeping the Go code. Please let me know.

**Comment by sachaos** [comment]
By the way, if I switch to Rust, will I have to change this Gopher logo? I really love this logo and don’t want to change it.

**Comment by rrotter** [comment]
Wow, that's a big change. Thanks for giving the community a heads up! Do you have any plans to make your rust branch public here before the 1.0 release? That would help package maintainers prepare.

**Comment by sachaos** [comment]
@rrotter Thank you for your comment!
Yes, I can do that!

**Comment by sachaos** [comment]
I've released v1.0.0-rc.0 https://github.com/sachaos/viddy/releases/tag/v1.0.0-rc.1 🎉

**Comment by sachaos** [comment]
I've released viddy v1.0.0-rc.2 🎉
Now, viddy can save and load history!
https://github.com/sachaos/viddy/releases/tag/v1.0.0-rc.2

**Comment by avamsi** [comment]
Big change indeed! I’ll check out the release candidates soon, but as someone who defaults to Go these days for simple programs, I’m curious about your experience with rewriting from Go to Rust. I understand this is somewhat unrelated to the main issue, and you might not be planning to discuss it, but if you are, I’d love to read about it. Thanks!

**Comment by avamsi** [comment]
Just got a chance to check out v1.0.0-rc.2, seems to work well other than the following --

1. Doesn't seem to handle tabs correctly
   - `viddy 'echo "1\t2"'` prints `12`
1. Doesn't seem to handle escape sequences correctly
   - `viddy 'echo "\e[34m blue \e[39m default \e[0m all"'` prints `default` in blue
1. Doesn't seem to support arrow keys for scrolling like the Go version
1. Horizontal scrolling seems to move by 10 columns instead of 1 like the Go version (I don't necessarily think this is worse, just reporting a difference I observed)

**Comment by sachaos** [comment]
@avamsi Thank you so much!
That's very helpful!

**Comment by sachaos** [comment]
@avamsi 
> Horizontal scrolling seems to move by 10 columns instead of 1 like the Go version (I don't necessarily think this is worse, just reporting a difference I observed)

Yes, this was an intentional change. The small scroll width was inconvenient, so I will also consider mouse support. Thank you.

**Comment by sachaos** [comment]
@avamsi 
> Doesn't seem to handle escape sequences correctly

I couldn't reproduce that.
When I run the command, the output is like following.
The same issue occurred with both the watch command and go viddy.

Can you share the backup file (the feature is included in rc.2)?

<img width="505" alt="スクリーンショット 2024-08-18 11 57 02" src="https://github.com/user-attachments/assets/320b6991-7ef8-4d2a-bab5-f8600e5fe0a8">

**Comment by avamsi** [comment]
> I couldn't reproduce that.

Oh. This is what the Go Version prints for me --
![Go Version](https://github.com/user-attachments/assets/76baa833-673f-4742-b928-176e2b284ce4)

And this is what the Rust version prints --
![Rust Version](https://github.com/user-attachments/assets/44880ec0-f687-4a67-964b-8aacea8de6f5)

`watch` doesn't work for me though --
![watch](https://github.com/user-attachments/assets/d4a922e3-f39c-405c-9151-f401dda5a400)

---

> Can you share the backup file (the feature is included in rc.2)?

Looks like I can't upload sqlite files here directly, I put it on Google Drive for now -- https://drive.google.com/file/d/11U-kjxFHC1glvlDpCToNZe2myWUc-uXt/view?usp=drive_link.

**Comment by avamsi** [comment]
Ah, looks like I was supposed to do `watch --color`, which works fine --
![watch --color](https://github.com/user-attachments/assets/d314985e-6aaf-4f02-aa4a-e4906f6fe376)

**Comment by sachaos** [comment]
@avamsi Thank you! What is the using OS?
Are you changing the shell in configuration files?

**Comment by avamsi** [comment]
> What is the using OS?

I'm currently on a Chromebook running Debian (via Crostini), I could test on a MacBook if you want.

> Are you changing the shell in configuration files?

Nope.

Are you unable to reproduce? What does just `echo '\e[34m blue \e[39m default \e[0m all'` print for you?

**Comment by sachaos** [comment]
@avamsi 

It seems like depending on shell.

- bash → fail
- sh → fail
- zsh → success

<img width="505" alt="スクリーンショット 2024-08-18 14 21 30" src="https://github.com/user-attachments/assets/37c58221-99ed-4bc1-8ee2-08dad05ad5c8">

I reproduced that issue by using zsh.

```
$ viddy --shell zsh 'echo "\e[34m blue \e[39m default \e[0m all"'
```

**Comment by avamsi** [comment]
Ah, I see -- yes, I use zsh.

**Comment by avamsi** [comment]
Looks like `echo -e '\e[34m blue \e[39m default \e[0m all'` should do the trick in Bash.

**Comment by sachaos** [comment]
@avamsi I think we have fixed the reported issues [1].
Thank you for your contributions (PR and issue reporting)! 🙏 

[1]: https://github.com/sachaos/viddy/issues/117#issuecomment-2294925153

**Comment by avamsi** [comment]
My pleasure! Thanks for fixing these quickly and in general, your work on viddy -- big fan!

**Comment by sachaos** [comment]
I have released viddy v1.0.0-rc.3 https://github.com/sachaos/viddy/releases/tag/v1.0.0-rc.3

**Comment by slashburygin** [comment]
Hi. Thank you very much for your project. Today I try new release v1.0.0-rc3 on centos7 forked system, but it requires new versions of glibc.
[centos@bootstrap build]$ viddy 
viddy: /lib64/libc.so.6: version `GLIBC_2.29' not found (required by viddy)
viddy: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by viddy)
viddy: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by viddy)
viddy: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by viddy)

Maybe is there a way to compile the program for a less recent version of glibc ?

**Comment by sachaos** [comment]
I have released viddy v1.0.0-rc.5 🎉 
I believe most of the problems have been solved. (Yes, there are still some issues and feature requests remaining.)
I'm planning to release v1.0.0 in a few days.

https://github.com/sachaos/viddy/releases/tag/v1.0.0-rc.5

**Comment by sachaos** [comment]
@slashburygin Thank you for the report!
I've released musl binary from v1.0.0-rc.5.
If you have time, please try it.

https://github.com/sachaos/viddy/releases/tag/v1.0.0-rc.5

**Comment by slashburygin** [comment]
Now all is ok, thank you very much. 
Small diff between versions: now interval option is integer, not float.

error: invalid value '1.8s' for '--interval <INTERVAL>': invalid float literal

**Comment by slashburygin** [comment]
Oh, sorry, now I can set interval without s, for example 1.8

**Comment by sachaos** [comment]
@slashburygin Thank you!
That behavior is not the same as the old version.
(The go version of Viddy can handle 1.8s)

However, it is a bit difficult to fix because the crate being used cannot handle it.
So I don't fix it now.
https://github.com/sachaos/viddy/issues/131

**Comment by sachaos** [comment]
I released viddy v1.0.0.
https://github.com/sachaos/viddy/releases

I submitted a PR to homebrew-core.
https://github.com/Homebrew/homebrew-core/pull/181977

**Comment by sachaos** [comment]
I close this announcement issue because v1.0.0 released.
If there are some problems, feel free to create a new issue.

We will track the status of the package registry in a separate issue.
https://github.com/sachaos/viddy/issues/136

**Comment by sachaos** [comment]
@avamsi 
> I’m curious about your experience with rewriting from Go to Rust.

I've written the blog post about my experience of migrating from Go to Rust.
If you are interested in, please read that!

https://dev.to/sachaos/release-of-viddy-v100-migration-from-go-to-rust-2g41

**Comment by avamsi** [comment]
Thanks for the writeup! Matches my experience / expectation trying out Rust here and there but more importantly, it's encouraging to see someone else go through the learning curve / trade offs etc. (and come out the other side)! :)
