### ISSUE TITLE
Add examples to how we can change the keybindings for the pager

### ISSUE THREAD

**Issue by sachaos** [sachaos/viddy#149]
### Discussed in https://github.com/sachaos/viddy/discussions/148

<div type='discussions-op-text'>

<sup>Originally posted by **Dominiquini** September  2, 2024</sup>
In the README, there are examples of how we could change the keybindings for the time machine (right panel). But I could´t find how change the keybinds for the default pager!

Thanks.</div>

**Comment by eshepelyuk** [comment]
Hello @sachaos 

Can you please add examples of how to configure `Pager: page down` , `Pager: page up` to `PgUp` and `PgDown` keys
as it worked previously, before 1.0.0.

**Comment by sachaos** [comment]
@eshepelyuk Oh, thank you for the report.
I think that's incompatibility bug.
I'll fix soon.

**Comment by eshepelyuk** [comment]
> @eshepelyuk Oh, thank you for the report. I think that's incompatibility bug. I'll fix soon.

Ahh, ok, thank you.

**Comment by sachaos** [comment]
@eshepelyuk I fixed the issue and released viddy v1.1.1 https://github.com/sachaos/viddy/releases/tag/v1.1.1
I think updating from registries like Homebrew will happen a little later.

**Comment by eshepelyuk** [comment]
> @eshepelyuk I fixed the issue and released viddy v1.1.1 https://github.com/sachaos/viddy/releases/tag/v1.1.1 I think updating from registries like Homebrew will happen a little later.

Thank you, as soon as it appeats in Homebrew - I'll update the issue.

**Comment by eshepelyuk** [comment]
@sachaos all works, thank you.

**Comment by Dominiquini** [comment]
> ### Discussed in #148
> 
> Originally posted by **Dominiquini** September 2, 2024 In the README, there are examples of how we could change the keybindings for the time machine (right panel). But I could´t find how change the keybinds for the default pager!
> 
> Thanks.

Any progress in updating the README to include examples of how change keybindings for the main panel?

Thanks.

**Comment by sachaos** [comment]
@Dominiquini I've developed this customizing feature and released v1.2.0.
