### ISSUE TITLE
`--shell fish` fish: unknown command: -c

### ISSUE THREAD

**Issue by anthr76** [sachaos/viddy#154]
Since the rust-rewrite; Running a command like `viddy --shell fish k get po` results in:

<img width="1227" alt="image" src="https://github.com/user-attachments/assets/fb1a51ce-362a-41ea-a51d-7214d6f14f16">

I tried to mess around with https://github.com/sachaos/viddy/blob/54cb024becec79bfbd0e45ec15a08841571d283c/src/exec.rs#L24 to no luck

**Comment by onedr0p** [comment]
I have the same issue, thanks for reporting @anthr76 👋🏼

**Comment by onedr0p** [comment]
@sachaos I found a workaround

```sh
viddy -d -n 2 --shell fish -c k get po```

Notice the `-c` after `fish`, hopefully this helps in finding the issue in the code.

**Comment by anthr76** [comment]
Fixed by https://github.com/sachaos/viddy/pull/155
