### ISSUE TITLE
viddy Crash Report - viddy -D -x "ps faux"

### ISSUE THREAD

**Issue by daniejstriata** [sachaos/viddy#158]
name = "viddy"
operating_system = "Linux Mint 21.3.0 (virginia) [64-bit]"
crate_version = "1.1.5"
explanation = """
Panic occurred in file 'src/runner.rs' at line 47
"""
cause = """
called `Result::unwrap()` on an `Err` value: 
   0: \u001B[91mNo such file or directory (os error 2)\u001B[0m"""
method = "Panic"
backtrace = """

   0: 0x7cec3f71bb06 - <unresolved>
   1: 0x7cec3f830b96 - <unresolved>
   2: 0x7cec3f82bc8d - <unresolved>
   3: 0x7cec3f7f006f - <unresolved>
   4: 0x7cec3fada621 - <unresolved>
   5: 0x7cec3fad99b8 - <unresolved>
   6: 0x7cec3faeb555 - <unresolved>
   7: 0x7cec3fad8dfa - <unresolved>
   8: 0x7cec3fadd0a3 - <unresolved>
   9: 0x7cec3fad4bb2 - <unresolved>
  10: 0x7cec3faf1468 - <unresolved>
  11: 0x7cec3fadde1f - <unresolved>
  12: 0x7cec3fade602 - <unresolved>
  13: 0x7cec3fc6413b - <unresolved>"""

**Comment by sachaos** [comment]
@daniejstriata Do you have reproducible example?

**Comment by sachaos** [comment]
@daniejstriata I've fixed the bug and released https://github.com/sachaos/viddy/releases/tag/v1.1.6 .
