### ISSUE TITLE
Sub second timing

### ISSUE THREAD

**Issue by SophisticaSean** [sachaos/viddy#16]
Would love to have sub-second (millisecond precision is fine) for Viddy!
I run `go test ./...` through viddy a lot to ensure I don't introduce any intermittent test failures and every second just isn't fast enough for me! 

Would you be open to me submitting a PR for sub-second precision on the `-n` flag?

**Comment by sachaos** [comment]
@SophisticaSean viddy is supporting sub-second.
You can specify the value like following.

watch style

```
viddy -n 0.5 ls
```

Go style

```
viddy -n 500ms ls
```

**Comment by sachaos** [comment]
I would like to close this issue.
If the above response was not suit for your requirements.
Feel free to reopen this.

**Comment by SophisticaSean** [comment]
thanks a ton! love viddy so thank you for your work on this
