### ISSUE TITLE
italic fonts

### ISSUE THREAD

**Issue by 00sapo** [sachaos/viddy#40]
I cannot render italic fonts.

For instance, use [`rich-cli`](https://github.com/Textualize/rich-cli) and [`unbuffer`](https://pkgs.org/search/?q=unbuffer&on=files) to render a markdown with italic fonts (my command is `unbuffer rich notes.md`). 

`unbuffer rich notes.md | less -r` and `watch -c unbuffer rich notes.md` render correctly, but `viddy unbuffer rich notes.md` doesn't work.

I'm using arch AUR package and konsole.

**Comment by sachaos** [comment]
This issue have been solved by viddy v1.0.0 RC.
https://github.com/sachaos/viddy/issues/117

**Comment by sachaos** [comment]
Viddy v1.0.0 is available now.
