### ISSUE TITLE
Option to save history?

### ISSUE THREAD

**Issue by theimpostor** [sachaos/viddy#52]
First of all, this project is really awesome, especially the time machine mode. Being able to scroll back through the historical snapshots of a commands output is just amazing. What would be nice is if there was a way to save / persist this information so that it could be attached to bug reports or reviewed at a later date after the viddy instance has exited. Perhaps just a raw text dump with some delimiter information between command output, like timestamp? Also would be cool to invoke the save interactively, via shortcut that prompts for a filename or something.

Thanks again for the awesome app.

**Comment by phanirithvij** [comment]
I think as of now this can be done externally using script command or asciinema but I can't say for sure what the pros and cons of having this feature inside viddy would be.

**Comment by sachaos** [comment]
I've implemented feature to save and load history in viddy v1.0.0-rc.2.

https://github.com/sachaos/viddy/issues/117#issuecomment-2294818886

**Comment by sachaos** [comment]
Viddy v1.0.0 is available now.
