### ISSUE TITLE
--unfold is a great option, but having a hotkey to toggle it would be better

### ISSUE THREAD

**Issue by Ghoughpteighbteau** [sachaos/viddy#53]
a key for wrapping (folding???) would be valuable.

It may be that you didn't realize a command was going to have long lines until after you executed it, as an argument you'd have to discard what results you have now to correct that.

In contexts where comparing the start of a line is helpful in finding the relevant part of output (like log outputs) then swapping back and forth between wrapped and unwrapped is helpful for navigation.

**Comment by coolabhays** [comment]
I've added 'u' hotkey for toggling unfold in #82

**Comment by Ghoughpteighbteau** [comment]
She's a beaut. Nice work!
