### ISSUE TITLE
quit viddy via 'q' key?

### ISSUE THREAD

**Issue by ryenus** [sachaos/viddy#63]
like in less.

BTW, nice idea for such _interactive watch_, kudos!

**Comment by cenkalti** [comment]
q is ubiquotus for quit. I can send PR if you merge.

**Comment by alexn-s** [comment]
q support would be great. like in lazygit

**Comment by coolabhays** [comment]
I've created one PR for this issue (soln. description in commit msg). Do tell, if it fits the requirement :)
