### ISSUE TITLE
AUR package out of date

### ISSUE THREAD

**Issue by bvobart** [sachaos/viddy#64]
Hi, I wanted to install `viddy` through your AUR package, but I noticed it is on v0.3.4-1 instead of the latest v0.3.6. I installed it with Go instead.

Can you fix the AUR package deployments? Thanks!

<sub>Great tool btw, very nice replacement for the old-school `watch`!</sub>

**Comment by sachaos** [comment]
Actually, I'm not the maintainer of that.
I would be happy if I could deploy a new version there automatically

**Comment by bvobart** [comment]
Ahh alright, no worries, I hope the maintainer gives you ownership over that some time, then it should be as easy as [pushing your updated code to the AUR Git repo](https://wiki.archlinux.org/title/AUR_submission_guidelines#Publishing_new_package_content).

**Comment by trancilo** [comment]
Just installed from AUR and got the newest version 0.3.6. Think this issue can be closed

**Comment by sachaos** [comment]
@llagerlof Hi, thank you for the feedback!
I've fixed the README.
https://github.com/sachaos/viddy/blob/master/README.md#install-with-other-package-managers-community-maintained
