### ISSUE TITLE
Cannot copy text from the viddy output window

### ISSUE THREAD

**Issue by live-wire** [sachaos/viddy#65]
- Using it on a Mac(x86) iterm2
- Cannot copy any text from the viddy output window
- Would be neat if I could

**Comment by kholisrag** [comment]
Yeah same with me, can't copy output from viddy,
Using ubuntu 20.04

**Comment by boeddeker** [comment]
On Ubuntu I can use shift to mark text and copy it. Not as comfortable as normally, but as a workaround it's ok.

**Comment by phanirithvij** [comment]
I was able to copy the output after hitting the `space` key, which pauses the output from changing.

**Comment by phanirithvij** [comment]
As of now, v1.0.2 copying works fine.

**Comment by sachaos** [comment]
Thank you let's close this.

**Comment by florianrusch** [comment]
> I was able to copy the output after hitting the `space` key, which pauses the output from changing.

This doesn't work for me on mac & iterm.
I already opened another issue for this (#153)
