### ISSUE TITLE
[feature-request] Shortcut to increase/decrease the interval

### ISSUE THREAD

**Issue by dadav** [sachaos/viddy#67]
Thanks for this awesome tool. It would be handy to be able to change the interval during runtime. I'm thinking about Ctrl-x for decreasing and Ctrl-a for increasing the interval. What do you think?

**Comment by sachaos** [comment]
I think that is interesting.
I think we need to discuss what unit of adjustment should be possible, and I wonder if it would be better to increase it exponential.
In any case, we are currently undergoing a major refactoring. If you are interested in implementing it, it would be better to start after that is done.

**Comment by phanirithvij** [comment]
[btop](https://github.com/aristocratos/btop) has it as increments of 100ms (100ms - inf) and keys -, + mapped.
