### ISSUE TITLE
Allow to use arrow keys for time machine movements 

### ISSUE THREAD

**Issue by secustor** [sachaos/viddy#7]
The shift+ shortcuts are not intuitive on the first glance. I think it would be good idea to map them parallely with arrow keys: 

- arrow_up: move 1 position to the future
- shift + arrow_up: move several positions to the future
- ctrl + shift + arrow_up: move to the newest position

- arrow_down: move 1 position to the past 
- shift + arrow_down: move several positions to the past
- ctrl + shift + arrow_down: move to the oldest position

I would look into implementing this myself if there is an interest in this feature.

**Comment by sachaos** [comment]
Thank you.
Actually, I don't like keybindings with the arrow keys.
But I can understand the demand.

So we should implement the feature to change the keybindings by configuration.
I'm interested in implementing the configuration feature, and I would like to implement this ASAP.

**Comment by secustor** [comment]
In that case I would suggest to migrate first to a config framework ( I would suggest  [Viper](https://github.com/spf13/viper)).

**Comment by sachaos** [comment]
Now, we can customize keymappings.

```
[keymap]
timemachine_go_to_past = "Down"
timemachine_go_to_more_past = "Shift-Down"
timemachine_go_to_future = "Up"
timemachine_go_to_more_future = "Shift-Up"
timemachine_go_to_now = "Ctrl-Shift-Up"
timemachine_go_to_oldest = "Ctrl-Shift-Down"
```
