### ISSUE TITLE
Releases should be inside a folder

### ISSUE THREAD

**Issue by sr105** [sachaos/viddy#72]
I ran the Linux wget and tar install command and it unpacked three files into my current directory. It should have unpacked into a directory like "viddy_0.3.6" so it doesn't overwrite any files in the current directory.

**Comment by phanirithvij** [comment]
As of now this issue doesn't exist, can be closed
```shell
❯ tar xf ../viddy-v1.0.2-linux-x86_64.tar.gz
❯ ls
viddy
```

**Comment by sachaos** [comment]
Thank you for the confirmation
Yes, let's close this.
