### ISSUE TITLE
Display error

### ISSUE THREAD

**Issue by YHYJ** [sachaos/viddy#80]
<img width="1538" alt="截屏2022-11-01 11 42 48" src="https://user-images.githubusercontent.com/21995281/199154232-cdd4f09f-b997-48de-9c67-270c3fe5d227.png">

↖️'Every' and '1s' are not fully display.

Tested on iTerm2 for macOS and Terminator for Linux.

**Comment by sachaos** [comment]
I think this issue is solved now.
If you have problem yet, please feel free to reopen!
