### ISSUE TITLE
FR: support horizontal scrolling

### ISSUE THREAD

**Issue by avamsi** [sachaos/viddy#87]
Maybe when `--unfold` is used.

**Comment by sachaos** [comment]
This issue fixed by v1.0.0-rc.1 https://github.com/sachaos/viddy/issues/117#issuecomment-2291069041

**Comment by avamsi** [comment]
I was just testing this for https://github.com/sachaos/viddy/issues/117#issuecomment-2294925153 and the Go version already supported horizontal scrolling?!

Perhaps it's worth advertising it in the Key Bindings help section going forward? Also, any chance of adding mouse support? Just scroll for vertical scrolling and shift+scroll for horizontal scrolling would be nice.

**Comment by sachaos** [comment]
I've added the keybindings to help.
I think the mouse support feature is another issue. https://github.com/sachaos/viddy/issues/137
I'll create the issue. Thank you!
