### ISSUE TITLE
Feature request: alias support

### ISSUE THREAD

**Issue by davidandradeduarte** [sachaos/viddy#9]
Hi,

Thank you for developing viddy!

I think one thing that could be a really good improvement over the current `watch` command is adding **support for aliases**.

Currently there's a bunch of work-arounds to get watch to work with aliases.

If viddy could add native support to use aliases, that would attract a lot of attention.

**Comment by Croissong** [comment]
Duplicate of #2 i think ;)

**Comment by davidandradeduarte** [comment]
Yeah, it's the same feature request. My bad for not looking at the already open issues.
https://github.com/sachaos/viddy/issues/2
