### ISSUE TITLE
Do not intercept or re-parse positional arguments

### ISSUE THREAD

**Issue by ahmetb** [sachaos/viddy#92]
While using 

    viddy curl -d '{"key": "value"}' [...]

I got an error from the command indicating that it's got too many positional args, it was immediately clear `viddy` is doing something with the `'{"fqdn": "lor1-foo"}'` argument (which is supposed to be a single `argv` in OS exec API) and now it's parsed into two arguments since it contains spaces.

It turns out viddy executes a sub-shell via bash and passes args via `*sh -c "..."`.

https://github.com/sachaos/viddy/blob/e39d4ce3fd4b2a9efd3b33b96dd10a81adb64c9b/snapshot.go#L106-L112

This is a poor idea in my opinion. While it may get a few things like bash aliases working, this causes inputs to be re-interpreted. **To overcome this, one must double-escape and be aware that viddy executes a bash under the covers and the args you give viddy are joined by a space character, which is poor experience.**, e.g.

    viddy curl -d \'{\"key\": \"value\"}\' [...]

Shlexing and shell escaping are not easy feats to pull off in a compatible way across shells. So I recommend a way to disabling this sort of wrapping entirely and just do an exec with the cmdline arguments, just like GNU watch(1) does.

**Comment by sachaos** [comment]
@ahmetb Thank you I've added `--no-shell` option.

I was unsure about whether the current implementation was really a good idea or not.
So your opinion was very helpful. Thank you.

I added the --no-shell option. I didn't want to break compatibility, so I implemented it as an option. However, by writing a configuration file, there should be no need to set it every time.

**Comment by ahmetb** [comment]
Thanks for fixing this. Since it's an interactive tool I'd recommend making it the default so it has a chance of being the default mode of operation long term, and people can adjust fairly easily. But it unblocks me already so thanks.
